[package]
name = "sntpc"
version = "0.4.0"
description = "Library for making SNTP requests"
homepage = "https://github.com/vpetrigo/sntpc"
repository = "https://github.com/vpetrigo/sntpc"
documentation = "https://docs.rs/sntpc"
readme = "README.md"
categories = ["date-and-time", "no-std", "embedded", "asynchronous"]
keywords = ["sntp", "ntp", "sntp-client", "ntp-client"]
license = "BSD-3-Clause"
authors = ["Vladimir Petrigo <vladimir.petrigo@gmail.com>"]
edition = "2021"
autoexamples = false

exclude = [
    ".github/*",
    "CONTRIBUTING.md",
    ".*",
]

[features]
default = ["std"]
std = []
utils = ["std", "chrono/clock"]
async = []
async_tokio = ["std", "async", "tokio"]
embassy = ["embassy-net", "async"]

[dependencies]
log = { version = "~0.4", optional = true }
chrono = { version = "~0.4", default-features = false, optional = true }
tokio = { version = "1", features = ["full"], optional = true }
embassy-net = { version = "0.5.0", features = [ "udp", "proto-ipv4", "proto-ipv6", "medium-ip"], optional = true }

[badges]
maintenance = { status = "actively-developed" }
