[package]
name = "example-simple-no-std"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sntpc = { path = "../../sntpc", default-features = false, features = ["async"] }
executor = "0.8.4"
