[package]
name = "example-timesync"
version = "0.1.0"
edition = "2021"
publish = false

[features]
log = ["simple_logger"]

[dependencies]
sntpc = { path = "../../sntpc", default-features = false, features = ["utils"] }
clap = { version = "2.33", default-features = false }
simple_logger = { version = "~1.13" , optional = true}