[package]
name = "example-tokio"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sntpc = { path = "../../sntpc", features = ["tokio-socket"] }
tokio = { version = "1", features = ["rt", "net", "macros", "time"] }
