name: 'sntpc test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy with all features
        run: cargo clippy --workspace --exclude example-simple-no-std --all-features -- -D clippy::all -D clippy::pedantic
      - name: Run clippy with no_std
        run: cargo clippy -p example-simple-no-std --no-default-features --profile no-std -- -D clippy::all -D clippy::pedantic
  clippy-nightly:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain add nightly
      - name: Install clippy
        run: rustup component add clippy --toolchain nightly
      - name: Run clippy for async feature
        run: cargo +nightly clippy --workspace --exclude example-simple-no-std --all-features -- -D clippy::all -D clippy::pedantic
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with std
        run: cargo build --workspace --exclude example-simple-no-std --all-features
      - name: Build with no_std
        run: |
          cargo build -p sntpc --no-default-features
          cargo build -p example-simple-no-std --profile no-std
      - name: Run tests with std
        run: cargo test
      - name: Run tests with no_std
        run: cargo test --no-default-features
