name: 'sntpc test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy with std
        run: cargo clippy --no-default-features --features="std log utils"
      - name: Run clippy with no_std
        run: cargo clippy --no-default-features --features="log"
      - name: Run clippy for tokio feature
        run: cargo clippy --features="tokio"
  clippy_async_no_std:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Install nightly toolchain
        run: rustup toolchain add nightly
      - name: Run clippy for async feature
        run: cargo +nightly clippy --no-default-features --features="async"
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --check
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with std
        run: cargo build --all --no-default-features --features="std utils"
      - name: Build with no_std
        run: cargo build --all --no-default-features
      - name: Run tests with std
        run: cargo test
      - name: Run tests with no_std
        run: cargo test --no-default-features
