name: 'sntpc test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy with all features
        run: cargo clippy --workspace --exclude example-simple-no-std --exclude example-smoltcp-request --exclude example-embassy-net --all-features -- -D clippy::all -D clippy::pedantic
      - name: Run clippy on examples
        run: |
          cargo clippy -p example-simple-no-std --no-default-features --profile no-std -- -D clippy::all -D clippy::pedantic
          cargo clippy -p example-smoltcp-request --all-features -- -D clippy::all -D clippy::pedantic
          cargo clippy -p example-embassy-net --all-features -- -D clippy::all -D clippy::pedantic
  clippy_async_no_std:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain add nightly
      - name: Install clippy
        run: rustup component add clippy --toolchain nightly
      - name: Run clippy for async feature
        run: cargo +nightly clippy --no-default-features --features="async" -- -D clippy::all -D clippy::pedantic
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with std
        run: cargo build --workspace --exclude example-simple-no-std --exclude example-smoltcp-request --exclude example-embassy-net --all-features
      - name: Build with no_std
        run: cargo build -p sntpc --no-default-features
      - name: Build examples
        run: |
          cargo build -p example-simple-no-std --profile no-std
          cargo build -p example-smoltcp-request --all-features
          cargo build -p example-embassy-net --all-features
      - name: Run tests with std
        run: cargo test
      - name: Run tests with no_std
        run: cargo test --no-default-features
